import job from "../services/job";
import user from "../services/user";
import chat from "../services/chat";
import recommend from "../services/recommend";
import pay from "../services/pay";
import about from "./about";
import students from "../services/students";
import jobs from "../services/jobs";

export default (app: any) => {
  app.route("/about").get(about);
  app.route("/job/:id").get(job.get);
  app.route("/job").post(job.create);
  app.route("/job/:id").delete(job.delete);
  app.route("/job/:id").patch(job.update);
  app.route("/job/:id/claim").post(job.claim);
  app.route("/user/:id").get(user.get);
  app.route("/user/:id").put(user.create);
  app.route("/user/:id").delete(user.delete);
  app.route("/user/:id").patch(user.update);
  app.route("/user/:id/jobs").get(jobs.getMyJobs);
  app.route("/user/locate").post(user.locate);
  app.route("/chat/:id").get(chat.get);
  app.route("/chat").post(chat.create);
  app.route("/chat/:id").delete(chat.delete);
  app.route("/chat/:id").patch(chat.update);
  app.route("/chat/:id/message").post(chat.sendMessage);
  app.route("/recommend/add").post(recommend.add);
  app.route("/recommend/request").post(recommend.request);
  app.route("/pay/connectStripe").get(pay.connectStripe);
  app.route("/pay/charge").post(pay.charge);
  app.route("/pay/addCard").post(pay.addCard);
  app.route("/students").get(students.getNearby);
  app.route("/jobs").get(jobs.getNearbyJobs);
};
