import job from "../services/job";
import user from "../services/user";
import chat from "../services/chat";
import recommend from "../services/recommend";
import pay from "../services/pay";
import about from "./about";
import students from "../services/students";
import jobs from "../services/jobs";
import images from "../services/images";

export default (app: any) => {
  app.route("/about").get(about);
  app.route("/job/:jobId").get(job.get);
  app.route("/job").post(job.create);
  app.route("/job/:jobId").delete(job.delete);
  app.route("/job/:jobId").patch(job.update);
  app.route("/job/:jobId/claim").post(job.claim);
  app.route("/user/:uid").get(user.get);
  app.route("/user/:uid").put(user.create);
  app.route("/user/:uid").delete(user.delete);
  app.route("/user/:uid").patch(user.update);
  app.route("/user/:uid/image").get(images.getUser);
  app.route("/user/:uid/jobs").get(jobs.getMyJobs);
  app.route("/user/:uid/chats").get(chat.getChats);
  app.route("/user/locate").post(user.locate);
  app.route("/chat/:chatId").get(chat.get);
  app.route("/chat").post(chat.create);
  app.route("/chat/:chatId").delete(chat.delete);
  app.route("/chat/:chatId").patch(chat.update);
  app.route("/chat/:chatId/message").post(chat.sendMessage);
  app.route("/recommend/add").post(recommend.add);
  app.route("/recommend/request").post(recommend.request);
  app.route("/pay/connectStripe").get(pay.connectStripe);
  app.route("/pay/charge").post(pay.charge);
  app.route("/pay/addCard").post(pay.addCard);
  app.route("/students").get(students.getNearby);
  app.route("/jobs").get(jobs.getNearbyJobs);
};
